name: Release CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, test
        run: |
          npm ci
          npm run build
          npm run test
        env:
          CI: true
      # note this will be _wrong_ until we configure a detatched head with the current version tagged at the diverged commit
      - name: find next version
        id: next_semver
        uses: bengreenier-actions/gh-release-next-semver@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          use_tag_name: true
          strip_tag_prefix: "v"
          type: "auto"
      - name: configure git for versioning
        run: |
          git config --global user.name overlayed-app-bot
          git config --global user.email bot@overlayed.app
          git config --global credential.helper store
          echo https://overlayed-app-bot:${{ secrets.GH_TOKEN }}@github.com > ~/.git-credentials
      - name: create tag
        run: |
          git add --force dist/
          git commit -m "Release v${{ steps.next_semver.outputs.next }} [skip ci]"
          git tag v${{ steps.next_semver.outputs.next }}
          git push origin v${{ steps.next_semver.outputs.next }}
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ steps.next_semver.outputs.next }}
          release_name: Release v${{ steps.next_semver.outputs.next }}
          draft: false
          prerelease: false
